Add option to choose which type of image to show in changelog
HermesGermany/galapagos pull request #166
Opened 2022-03-21 10:07 UTC by ueberschaersilas-hg

Need to be logged in to outlook in the same browser to user outlook images!

2022-05-13 12:43 UTC, albrechtflo-hg requested changes

2022-05-13 12:43 UTC, albrechtflo-hg commented on ui/src/app/layout/dashboard/dashboard.component.html
> +                                      <img class="image1" src='{{getDefaultPicture(change.principal)}}'>
Should be an Observable, no direct method invocation (Angular will call that method a dozen times)

2022-05-13 12:43 UTC, albrechtflo-hg commented on ui/src/app/layout/dashboard/dashboard.component.html
> +                                      <img class="image2" src='{{getProfilePicture(change.principal)}}'>
See above

2022-05-13 12:43 UTC, albrechtflo-hg commented on ui/src/app/layout/dashboard/dashboard.component.ts
> +        switch (this.changelogDefaultPicture.toLowerCase()) {
Code could be combined with getProfilePicture  (e.g. `getPicture(user: string, pictureType: string)` )

2022-06-14 11:01 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.scss
> +
empty lines can be deleted

2022-06-14 11:03 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.scss
> +.image2 {
see above => "profileImage"

2022-06-14 11:05 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.ts
> +            console.log('GET PROFILE PICTURE');
:O

2022-06-14 11:31 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.ts
> +            console.log('GET DEFAULT PICTURE');
please remove

2022-06-14 11:34 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.html
> +                                </div>
why render two images here? I checked the look of this in the UI and i think this here is not how it should be

2022-06-21 21:42 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.ts
> +        firstValueFrom(this.serverInfoService.getUiConfig()).then(r => {
r => config better

2022-06-28 13:34 UTC, albrechtflo-hg requested changes

2022-06-28 13:34 UTC, albrechtflo-hg commented on src/main/java/com/hermesworld/ais/galapagos/changes/config/GalapagosChangesConfig.java
> +import com.hermesworld.ais.galapagos.uisupport.controller.ProfilePicture;
Dependency violation: A "config" package (or, the "changes" "module") should not be dependent on "uisupport" package. Please move ProfilePicture here, in this Config package.

2022-06-28 13:34 UTC, albrechtflo-hg commented on ui/src/app/layout/dashboard/dashboard.component.ts
> +            image.src = change.defaultPictureUrl;
Instead of accessing img directly, you can set `change.profilePictureUrl = change.defaultPictureUrl` here.

2022-06-30 15:22 UTC, albrechtflo-hg approved these changes

2022-06-30 15:27 UTC, merged