Skip schema compatibility check as admin
HermesGermany/galapagos pull request #170
Opened 2022-03-23 11:04 UTC by PolatEmre-hg

closes #169

2022-05-13 12:39 UTC, albrechtflo-hg commented
Currently merge conflicts, please resolve

2022-06-14 09:14 UTC, PolatEmre-hg commented
> Currently merge conflicts, please resolve

2022-06-15 14:09 UTC, albrechtflo-hg commented on src/main/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImpl.java
> +                if (!skipCompatCheck) {
Could be included in condition in line 435 - whole block does not need to be executed if `skipCompatCheck` is active.

2022-06-15 14:10 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/controller/TopicControllerTest.java
>          when(applicationsService.isUserAuthorizedFor("app-9")).thenReturn(true);
Please add two tests, testing the currentUser.isAdmin check (positive and negative case) when the `skipCompatCheck` flag is active.

2022-06-15 14:11 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +        SchemaMetadata newSchemaMetadata = service.addTopicSchemaVersion("test", schema2, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", schema1, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", schema2, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", "topic-1", "{ \"title\": 17 }", null, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", "topic-1", "{", null, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", "topic-1", testJsonSchema, null, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +        service.addTopicSchemaVersion("test", "topic-1", testJsonSchema, null, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", "topic-1", testJsonSchema, null, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +        service.addTopicSchemaVersion("test", "topic-1", testJsonSchema, null, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +        service.addTopicSchemaVersion("test", newSchema, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:12 UTC, albrechtflo-hg commented on src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
> +            service.addTopicSchemaVersion("test", newSchema, false).get();
Parameter should be set to true to have previous behaviour here

2022-06-15 14:13 UTC, albrechtflo-hg commented on ui/src/app/layout/createtopic/createtopic.component.ts
> +        return this.topicsSerivce.addTopicSchema(topicName, environmentId, jsonSchema, false).then(
Won't work if current user is not admin?!

2022-06-15 14:15 UTC, albrechtflo-hg commented on ui/src/app/layout/topics/schemasection/schema-section.component.html
> +                                       [(ngModel)]="skipCompatCheck"> {{ 'Skip compatibility check' | translate }}
An `ngb-alert` with warning type should be included here and state, "**Caution**: This allows for incompatible changes in the topic data. Only use this if you really know what you are doing."

The alert should only be displayed when the checkbox is checked.

2022-06-21 13:39 UTC, albrechtflo-hg commented
Ignore all my "parameter must be true for previous behaviour" comments. Of course, "false" is correct, I misthought it for being "check yes / no" (instead of "skip check yes/no").

2022-06-28 13:45 UTC, albrechtflo-hg commented on ui/src/assets/i18n/de.json
> +    "SKIP_COMBAT_CHECK_WARNING": "<b>Achtung</b>: Dies ermöglicht inkompatible Änderungen in den Topic Daten. Verwende dies nur, wenn du wirklich weißt, was du tust."
No, no combat please, stop war! ;-)  (Please rename key to SKIP_COMPAT_...)

2022-06-28 13:46 UTC, albrechtflo-hg requested changes
Please rename SKIP_COMBAT_... to SKIP_COMPAT

2022-06-28 15:06 UTC, albrechtflo-hg approved these changes

2022-06-28 15:24 UTC, merged