Change toPromise to FirstValueFrom
HermesGermany/galapagos pull request #172
Opened 2022-03-28 14:33 UTC by ueberschaersilas-hg

2022-05-13 12:36 UTC, albrechtflo-hg commented
Currently merge conflicts, please resolve

2022-06-14 12:30 UTC, PolatEmre-hg commented
looks good to me :)

2022-06-16 14:17 UTC, albrechtflo-hg requested changes
We could (and should) also remove all related `take(1)`s, as `firstValueFrom`, according to the docs, resolves "as soon as the first value arrives", so no need to artificially crop the Observable.

2022-06-21 13:16 UTC, albrechtflo-hg requested changes

2022-06-21 13:16 UTC, albrechtflo-hg commented on ui/src/app/shared/services/topics.service.ts
> -            this.applicationsService.getAvailableApplications(false)]).pipe(map(values => toTopicArray(values))).pipe(take(1));
Must also be kept.

2022-06-22 11:39 UTC, merged