Show Kafka Instance Name in UI
HermesGermany/galapagos pull request #182
Opened 2022-04-22 12:36 UTC by ahmedullah-neyazi-hg

Closes #181

2022-05-13 07:33 UTC, albrechtflo-hg approved these changes

2022-05-13 12:32 UTC, albrechtflo-hg requested changes

2022-05-13 12:32 UTC, albrechtflo-hg commented on ui/src/app/layout/dashboard/dashboard.component.html
> +                    <strong>Kafka Instance:</strong>&nbsp;&nbsp;
Should be "Galapagos Instance"

2022-06-14 14:19 UTC, PolatEmre-hg commented on ui/src/app/layout/dashboard/dashboard.component.html
> +                    <code>{{ instanceNameInfo | async }}</code>
i am not sure, but since we now show the name in the header, this can be deleted from the dashboard i would say

2022-07-05 11:49 UTC, albrechtflo-hg requested changes

2022-07-05 11:49 UTC, albrechtflo-hg commented on src/main/resources/application.properties
> +info.galapagos.instanceName=Confluent Kafka
Default value should be empty, and a comment should describe what this value does.

2022-07-05 11:49 UTC, albrechtflo-hg commented on ui/src/app/shared/services/serverinfo.service.ts
> +    galapagos: {
Should be optional, like toggles.

2022-07-05 12:52 UTC, albrechtflo-hg approved these changes

2022-07-05 12:53 UTC, merged